# Cloud Build configuration for demo-service
# This pipeline builds, tests, and deploys the TypeScript service to Cloud Run

steps:
  # Step 1: Install dependencies
  - name: 'node:18-slim'
    entrypoint: npm
    args: ['install']
    id: 'install-dependencies'

  # Step 2: Compile TypeScript
  - name: 'node:18-slim'
    entrypoint: npm
    args: ['run', 'postinstall']
    id: 'compile-typescript'
    waitFor: ['install-dependencies']

  # Step 3: Build Docker image
  # Uses git commit SHA for versioning
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-docker-image'
    waitFor: ['compile-typescript']

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}'
    id: 'push-docker-image'
    waitFor: ['build-docker-image']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_PREFIX}-${_SERVICE_NAME}'
      - '--image=europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--service-account=${_SERVICE_ACCOUNT}'
      - '--allow-unauthenticated'
      - '--set-env-vars=BUCKET_NAME=${_PREFIX}-${_BUCKET_NAME},SECRET_NAME=${_PREFIX}-${_SECRET_NAME}'
    id: 'deploy-cloud-run'
    waitFor: ['push-docker-image']

# Substitution variables
# Update these to match your Terraform configuration
substitutions:
  _PREFIX: 'al'  # Must match your prefix in terraform.tfvars
  _SERVICE_NAME: 'demo-service'
  _REGION: 'europe-west1'
  _BUCKET_NAME: 'curamet-bucket'  # Actual bucket name without prefix
  _SECRET_NAME: 'demo-secret'  # Actual secret name without prefix
  _SERVICE_ACCOUNT: 'al-sa-demo-service-runner@curamet-onboarding.iam.gserviceaccount.com'  # Service account with al prefix

# Store images in Artifact Registry
images:
  - 'europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}:${SHORT_SHA}'
  - 'europe-docker.pkg.dev/${PROJECT_ID}/${_PREFIX}-curamet-repo/${_PREFIX}-${_SERVICE_NAME}:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for the entire build (default is 10 minutes)
timeout: '1200s'
